### ISSUE TITLE
reddit comments

### ISSUE THREAD

**Issue by mschettler** [nebez/smartstart#1]
what about an ability to go to the reddit comments for a given post on the dashboard?

**Comment by nebez** [comment]
Good idea, I will work on trying to implement this. It will likely mean modifying the layout slightly, but I'll try my best to keep the simplicity in tact.

**Comment by nehalvpatel** [comment]
I don't think this should be a thing, because it wouldn't really fit the page. As it is, the page is designed to give quick bits of information, and adding comments would make it way more cluttered than it needs to be.

**Comment by mschettler** [comment]
Just a subtle link to access them. Otherwise there's no real way to read them from the site because you can only click into the article and you skip reddit entirely 

-Matt

**Comment by nehalvpatel** [comment]
Oh sorry I misunderstood that. This should definitely be added.

**Comment by mschettler** [comment]
see my pull request, ive added this without changing the UI at all.
